package com.example.MyBookShopApp.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.Set;

@Entity
@Table(name = "authors")
@ApiModel(description = "data model of author enrity")
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "author id generated by db",position = 1)
    private Integer id;

    @ApiModelProperty(value = "author photo")
    private String photo;

    @ApiModelProperty(value = "author mnemonical id")
    private String slug;

    @ApiModelProperty(value = "author name")
    private String name;

    @Column(length = 2048)
    @ApiModelProperty(value = "author description")
    private String description;

    @OneToMany(mappedBy = "author")
    @JsonIgnore
    private Set<Book2Author> book2Author;

    @Transient
    @JsonIgnore
    private String firstName;

    @Transient
    @JsonIgnore
    private String lastName;

    @Override
    public String toString() {
        return name;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<Book2Author> getBook2Author() {
        return book2Author;
    }

    public void setBook2Author(Set<Book2Author> book2Author) {
        this.book2Author = book2Author;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}
